config/routes.rb
Rails.application.routes.draw do

  get 'series_images/index' , to: 'series_images#index', as: 'series_images'

  get 'series_images/new'

  get 'series_images/create'

  get 'series_images/update'

  post 'series_images/update'

  resources :skus
  get '/price_managements/index', :controller => 'price_managements', :action => 'index'
  post '/price_managements/index', :controller => 'price_managements', :action => 'index'
  get '/product_images/index', :controller => 'product_images', :action => 'index'
  post '/product_images/index', :controller => 'product_images', :action => 'index'
  get '/site_skus/index', :controller => 'site_skus', :action => 'index'
  post '/site_skus/index', :controller => 'site_skus', :action => 'index'
  get '/baby_managements/index', :controller => 'baby_managements', :action => 'index'
  post '/baby_managements/index', :controller => 'baby_managements', :action => 'index'
    
  resources :baby_managements
  resources :product_managements
  resources :price_managements
  resources :users
  resources :products
  resources :site_skus
  root 'sessions#create'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :product_images

end

app/models/product_management.rb
# == Schema Information
#
# Table name: product_managements
#
#  id         :integer          not null, primary key
#  sku        :string
#  tag        :string
#  position   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ProductManagement < ActiveRecord::Base
end

app/controllers/product_managements_controller.rb
class ProductManagementsController < ApplicationController
  before_action :set_product_management, only: [:show, :edit, :update, :destroy]

  # GET /product_managements
  # GET /product_managements.json
  def index
    @product_managements = ProductManagement.all
  end

  # GET /product_managements/1
  # GET /product_managements/1.json
  def show
  end

  # GET /product_managements/new
  def new
    @product_management = ProductManagement.new
  end

  # GET /product_managements/1/edit
  def edit
  end

  # POST /product_managements
  # POST /product_managements.json
  def create
    @product_management = ProductManagement.new(product_management_params)

    respond_to do |format|
      if @product_management.save
        format.html { redirect_to @product_management, notice: 'Product management was successfully created.' }
        format.json { render :show, status: :created, location: @product_management }
      else
        format.html { render :new }
        format.json { render json: @product_management.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_managements/1
  # PATCH/PUT /product_managements/1.json
  def update
    respond_to do |format|
      if @product_management.update(product_management_params)
        format.html { redirect_to @product_management, notice: 'Product management was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_management }
      else
        format.html { render :edit }
        format.json { render json: @product_management.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_managements/1
  # DELETE /product_managements/1.json
  def destroy
    @product_management.destroy
    respond_to do |format|
      format.html { redirect_to product_managements_url, notice: 'Product management was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_management
      @product_management = ProductManagement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_management_params
      params.require(:product_management).permit(:sku, :tag, :position)
    end
end

app/helpers/product_managements_helper.rb
module ProductManagementsHelper
end

app/views/product_managements/_form.html.erb
<div class="col-md-11 col-xs-11 cont_right" style="margin-left:8.3333333333%;margin-top:20px;">
  <%= form_for(@product_management) do |f| %>
    <% if @product_management.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@product_management.errors.count, "error") %> prohibited this product_management from being saved:</h2>

        <ul>
        <% @product_management.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row">
      <div class="col-md-4 form-group field">
        <%= f.label :sku %><br>
        <%= f.text_field :sku,class: 'form-control' %>
      </div>
      <div class="col-md-4 form-group field">
        <%= f.label :tag %><br>
        <%= f.text_field :tag,class: 'form-control' %>
      </div>
      <div class="col-md-4 form-group field">
        <%= f.label :position %><br>
        <%= f.number_field :position,class: 'form-control' %>
      </div>
      <div class="col-md-4 form-group field">
        <%= f.label :series %><br>
        <%= f.text_field :position,class: 'form-control' %>
      </div>
      <div class="col-md-4 form-group field">
        <%= f.label :image %><br>
        <%= f.file_field :image_file,class: 'form-control',style: 'height:40px;' %>
      </div>
    </div>
    <div class="row" style="margin-top:20px;margin-left:20px;">
      <div class="actions">
        <%= f.submit "确定",class: 'btn btn-default' %>
        <%= link_to '返回', product_managements_path,class: 'btn btn-default' %>
      </div>
    </div>
  <% end %>
</div>

app/views/product_managements/edit.html.erb
<%= render 'form' %>

app/views/product_managements/index.html.erb
  <div class="col-md-11 col-xs-11 cont_right" style="margin-left:8.3333333333%;;">
    <div class="col-md-2 col-xs-5 ser_h"><input type="text" class="form-control" placeholder="输入你要查找的SKU"></div>
    <div class="col-md-2 col-xs-6 ser_h">
        <div class="col-md-6 col-xs-6 text-center line_h35">品类</div>
        <div class="col-md-6 col-xs-6 padt10">
          <select class="form-control">
            <option>全部</option>          
          </select>
        </div>
      </div>
      <div class="col-md-2 col-xs-6 ser_h">
        <div class="col-md-6 col-xs-6 text-center line_h35">类别</div>
        <div class="col-md-6 col-xs-6 padt10">
          <select class="form-control">
            <option>全部</option>          
          </select>
        </div>
      </div>
      <div class="col-md-2 col-xs-6 ser_h">
        <div class="col-md-6 col-xs-6 text-center line_h35">系列</div>
        <div class="col-md-6 col-xs-6 padt10">
          <select class="form-control">
            <option>全部</option>          
          </select>
        </div>
      </div>
      <div class="col-md-2 col-xs-6 ser_h">
        <div class="col-md-6 col-xs-6 text-center line_h35">规格</div>
        <div class="col-md-6 col-xs-6 padt10">
          <select class="form-control">
            <option>全部</option>          
          </select>
        </div>
      </div>
    <div class="col-md-1 col-xs-1 ser_h" style="background:#fff;"><button type="submit" class="btn btn-default" style="background:#78909c;color:#fff">搜索</button></div>
    <div class="col-md-12 col-xs-12 mt20">
      <%= link_to '新增产品', new_product_management_path,class: 'creat' %>
    </div>
    <div class="col-md-12 col-xs-12 text-center th_h" style="margin-top:10px;">
      <table style="width:100%;">
        <thead>
          <tr>
            <th class="col-md-1 text-center col-xs-1">SKU</th>
            <th class="col-md-1 text-center col-xs-1">品类</th>
            <th class="col-md-1 text-center col-xs-1">归类</th>
            <th class="col-md-1 text-center col-xs-1">类别</th>
            <th class="col-md-1 text-center col-xs-1">系列</th>
            <th class="col-md-1 text-center col-xs-1">规格</th>
            <th class="col-md-2 text-center col-xs-2">平台</th>
            <th class="col-md-1 text-center col-xs-1">状态</th>
            <th class="col-md-1 text-center col-xs-1">操作</th>
          </tr>
        </thead>

        <tbody>
          <% @product_managements.each do |product_management| %>
            <tr>
              <td><%= product_management.sku %></td>
              <td>二类目录</td>
              <td>二类目录</td>
              <td>三类目录</td>
              <td>四类目录</td>
              <td>600*900</td>
              <td>
                <%= check_box_tag(:age, "1",{},disabled:"disabled") %>
                <%= label_tag(:age_child, "E选材") %><br>
                <%= check_box_tag(:age, "2", false,disabled:"disabled") %>
                <%= label_tag(:age_child, "E找砖") %><br>
                <%= check_box_tag(:age, "3",{},disabled:"disabled") %>
                <%= label_tag(:age_child, "E分销") %><br>
                <%= check_box_tag(:age, "4", false,disabled:"disabled") %>
                <%= label_tag(:age_child, "E出口") %><br>
                <%= check_box_tag(:age, "5",{},disabled:"disabled") %>
                <%= label_tag(:age_child, "家居网") %><br>
              </td>
              <td style="color:red;">已上架</td>
              <td style="color:blue;">下架</td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
    </div>

app/views/product_managements/new.html.erb
<%= render 'form' %>

app/views/product_managements/show.html.erb
<div class="col-md-11 col-xs-11 cont_right" style="margin-left:8.3333333333%;margin-top:20px;">
	<%= form_for(@product_management) do |f| %>
	<div class="row">
		<div class="col-md-4 form-group field">
	      <%= f.label :Sku %><br>
	      <%= f.text_field :sku,class: 'form-control',disabled: 'disabled'%>
	    </div>
	    <div class="col-md-4 form-group field">
	      <%= f.label :Tag %><br>
	      <%= f.text_field :tag,class: 'form-control',disabled: 'disabled'%>
	    </div>
	    <div class="col-md-4 form-group field">
	      <%= f.label :Position %><br>
	      <%= f.text_field :position,class: 'form-control',disabled: 'disabled'%>
	    </div>
	</div>
	<div class="row" style="margin-top:20px;margin-left:20px;">
		<div class="actions">
		<%= link_to '编辑', edit_product_management_path(@product_management),class: 'btn btn-default' %>
		<%= link_to '返回', product_managements_path,class: 'btn btn-default' %>
		</div>
	</div>
	<% end %>
</div>