config/routes.rb
Rails.application.routes.draw do

  get 'series_images/index' , to: 'series_images#index', as: 'series_images'

  get 'series_images/new'

  get 'series_images/create'

  get 'series_images/update'

  post 'series_images/update'

  resources :skus
  get '/price_managements/index', :controller => 'price_managements', :action => 'index'
  post '/price_managements/index', :controller => 'price_managements', :action => 'index'
  get '/product_images/index', :controller => 'product_images', :action => 'index'
  post '/product_images/index', :controller => 'product_images', :action => 'index'
  get '/site_skus/index', :controller => 'site_skus', :action => 'index'
  post '/site_skus/index', :controller => 'site_skus', :action => 'index'
  get '/baby_managements/index', :controller => 'baby_managements', :action => 'index'
  post '/baby_managements/index', :controller => 'baby_managements', :action => 'index'
    
  resources :baby_managements
  resources :product_managements
  resources :price_managements
  resources :users
  resources :products
  resources :site_skus
  root 'sessions#create'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :product_images

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  employee_number :string
#  name            :string
#  mobile          :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  admin           :boolean          default(FALSE)
#

class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password validations: false
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.password = params[:user][:password]
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:employee_number, :name, :mobile, :password, :admin)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="col-md-11 col-xs-11 cont_right" style="margin-left:8.3333333333%;margin-top:20px;">
  <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  <div class="row">
    <div class="field">
      <div class="col-md-4 field col-xs-12">
        <div class="col-md-4 col-xs-4 pad_line"><%= f.label :员工编号 %></div>
        <div class="col-md-8 col-xs-8"><%= f.text_field :employee_number %></div>
      </div>
    </div>
    <div class="col-md-4 field col-xs-12">
      <div class="col-md-4 col-xs-4 pad_line"><%= f.label :员工姓名 %></div>
      <div class="col-md-8 col-xs-8"><%= f.text_field :name %></div>
    </div>
    <div class="col-md-4 field col-xs-12">
      <div class="col-md-4 col-xs-4 pad_line"><%= f.label :手机号码 %></div>
      <div class="col-md-8 col-xs-8"><%= f.text_field :mobile %></div>
    </div>
    <div class="col-md-4 field col-xs-12">
      <div class="col-md-4 col-xs-4 pad_line"><%= f.label :密码 %></div>
      <div class="col-md-8 col-xs-8"><%= f.text_field :password %></div>
    </div>
    <div class="col-md-4 field col-xs-12">
      <div class="col-md-4 col-xs-4 pad_line"><%= f.label :是否是管理员 %></div>
      <div class="col-md-8 col-xs-8"><%= f.text_field :admin %></div>
    </div>
  </div>
  <div class="row" style="margin-top:20px;margin-left:20px;">
    <div class="actions">
      <%= f.submit "确定",class: 'btn btn-default' %>
      <%= link_to '返回', users_path,class: 'btn btn-default' %>
    </div>
  </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<div class="col-md-11 col-xs-11 cont_right" style="margin-left:8.3333333333%;">
  <div class="col-md-12 col-xs-12 mt20">
    <div class="tab-content">
      <div class="tab-pane active" id="ceramic">
        <div class="col-md-12 col-xs-12 mt20">
          <%= link_to '新增用户', new_user_path,class: 'creat' %>
        </div>
        <div class="col-md-12 col-xs-12 text-center th_h" style="margin-top:20px;padding-left:0;padding-right:0;">
          <table style="width:100%;">
            <thead>
              <tr>
                <th class="col-md-2 text-center col-xs-2">员工编号</th>
                <th class="col-md-2 text-center col-xs-2">员工姓名</th>
                <th class="col-md-2 text-center col-xs-2">手机号码</th>
                <th class="col-md-2 text-center col-xs-2">加密密码</th>
                <th class="col-md-1 text-center col-xs-1">是否是管理员</th>
                <th class="col-md-3 text-center col-xs-3">操作</th>
              </tr>
            </thead>

            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td><%= user.employee_number %></td>
                  <td><%= user.name %></td>
                  <td><%= user.mobile %></td>
                  <td><%= user.password_digest %></td>
                  <% if user.admin %>
                  <td>是</td>
                  <% else %>
                  <td>否</td>
                  <% end %>
                  <td><%= link_to '查看', user ,class: 'text-center'%>&nbsp;&nbsp;<%= link_to '编辑', edit_user_path(user) ,class: 'text-center'%>&nbsp;&nbsp;<%= link_to '删除', user, method: :delete, data: { confirm: '真的要删除资料吗?' } ,class: 'text-center'%></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>  

  <%= link_to 'New User', new_user_path %>
  <%= link_to '退出', logout_path, method: :delete %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<div class="col-md-11 col-xs-11 cont_right" style="margin-left:8.3333333333%;margin-top:20px;">
	<%= form_for(@user) do |f| %>
		<div class="row">
			<div class="col-md-4 field col-xs-12">
				<div class="col-md-4 col-xs-4 pad_line"><%= f.label :员工编号 %></div>
				<div class="col-md-8 col-xs-8"><%= f.text_field :employee_number,class: 'form-control',disabled: 'disabled'%></div>
			</div>
			<div class="col-md-4 field col-xs-12">
				<div class="col-md-4 col-xs-4 pad_line"><%= f.label :员工姓名 %></div>
				<div class="col-md-8 col-xs-8"><%= f.text_field :name,class: 'form-control',disabled: 'disabled'%></div>
			</div>
			<div class="col-md-4 field col-xs-12">
				<div class="col-md-4 col-xs-4 pad_line"><%= f.label :手机号码 %></div>
				<div class="col-md-8 col-xs-8"><%= f.text_field :mobile,class: 'form-control',disabled: 'disabled'%></div>
			</div>
			<div class="col-md-4 field col-xs-12">
				<div class="col-md-4 col-xs-4 pad_line"><%= f.label :加密密码 %></div>
				<div class="col-md-8 col-xs-8"><%= f.text_field :password_digest,class: 'form-control',disabled: 'disabled'%></div>
			</div>
			<div class="col-md-4 field col-xs-12">
				<div class="col-md-4 col-xs-4 pad_line"><%= f.label :是否是管理员 %></div>
				<div class="col-md-8 col-xs-8"><%= f.text_field :admin,class: 'form-control',disabled: 'disabled'%></div>
			</div>
		</div>
		<div class="row" style="margin-top:20px;margin-left:20px;">
	      <div class="actions">
	        <%= link_to '编辑', edit_user_path(@user),class: 'btn btn-default' %>
	        <%= link_to '返回', users_path,class: 'btn btn-default' %>
	      </div>
      	</div>
	<% end %>
</div>