config/routes.rb
Rails.application.routes.draw do

  get 'series_images/index' , to: 'series_images#index', as: 'series_images'

  get 'series_images/new'

  get 'series_images/create'

  get 'series_images/update'

  post 'series_images/update'

  resources :skus
  get '/price_managements/index', :controller => 'price_managements', :action => 'index'
  post '/price_managements/index', :controller => 'price_managements', :action => 'index'
  get '/product_images/index', :controller => 'product_images', :action => 'index'
  post '/product_images/index', :controller => 'product_images', :action => 'index'
  get '/site_skus/index', :controller => 'site_skus', :action => 'index'
  post '/site_skus/index', :controller => 'site_skus', :action => 'index'
  get '/baby_managements/index', :controller => 'baby_managements', :action => 'index'
  post '/baby_managements/index', :controller => 'baby_managements', :action => 'index'
    
  resources :baby_managements
  resources :product_managements
  resources :price_managements
  resources :users
  resources :products
  resources :site_skus
  root 'sessions#create'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :product_images

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id                  :integer          not null, primary key
#  product_category_id :integer
#  product_no          :string
#  name                :string
#  description         :text
#  spec                :string
#  brand               :string
#  water_absrp_rate_id :integer
#  thickness           :decimal(, )
#  shape_id            :integer
#  color_id            :integer
#  cases_per_pallet    :integer
#  unit_weight         :decimal(, )
#  unit_area           :decimal(, )
#  package_weight      :decimal(, )
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  surface_craft_id    :integer
#  base_unit_id        :integer
#  business_unit_id    :integer
#  material_id         :integer
#  packing_unit        :integer
#  tabtype             :string
#

class Product < ActiveRecord::Base
  belongs_to :product_category
  belongs_to :root_product_category, class_name: "ProductCategory", foreign_key: :root_product_category_id
  belongs_to :rim_category
  belongs_to :material
  belongs_to :surface_craft
  belongs_to :water_absrp_rate
  belongs_to :shape
  belongs_to :color
  has_many :price_management, dependent: :destroy
  has_many :product_images, dependent: :destroy
  has_many :site_sku, dependent: :destroy
  has_many :sku, dependent: :destroy
  has_many :baby_management, dependent: :destroy

  validates_presence_of :product_no, :message => "产品编号不能为空"
  validates_presence_of :product_category_id, :message => "产品品类不能为空"
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:product] || params[:category] || params[:spec]
      @products = Product.where(root_product_category_id: '1').order("updated_at DESC").
       where("name LIKE ? OR product_no LIKE ? OR spec LIKE ?", params[:product], params[:product], params[:spec]).
                  #where(['product_category_id LIKE ?', "%#{params[:category]}%"]).
                  paginate page: params[:page], per_page: 20
      @mosaic = Product.where(root_product_category_id: '101').order("updated_at DESC").
       where("name LIKE ? OR product_no LIKE ? OR spec LIKE ?", params[:product], params[:product], params[:spec]).
                  #where(['product_category_id LIKE ?', "%#{params[:category]}%"]).
                  paginate page: params[:page], per_page: 20
    else
      @products = Product.where(root_product_category_id: '1').order("updated_at DESC").paginate page:params[:page], per_page: 20
      @mosaic = Product.where(root_product_category_id: '101').order("updated_at DESC").paginate page:params[:page], per_page: 20
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
=begin
    $last_data = Product.where(root_product_category_id: params[:root_product_category_id]).last
    params = {}
    params[:product_no] = $last_data.product_no
    params[:name] = $last_data.name
    params[:description] = $last_data.description
    params[:spec] = $last_data.spec
    params[:brand] = $last_data.brand
    params[:material_id] = $last_data.material_id
    params[:surface_craft_id] = $last_data.surface_craft_id
    params[:water_absrp_rate_id] = $last_data.water_absrp_rate_id
    params[:thickness] = $last_data.thickness
    params[:shape_id] = $last_data.shape_id
    params[:color_id] = $last_data.color_id
    params[:cases_per_pallet] = $last_data.cases_per_pallet
    params[:base_unit_id] = $last_data.base_unit_id
    params[:unit_weight] = $last_data.unit_weight
    params[:unit_area] = $last_data.unit_area
    params[:business_unit_id] = $last_data.business_unit_id
    params[:packing_unit] = $last_data.packing_unit
    params[:package_weight] = $last_data.package_weight
    params[:rim_category_id] = $last_data.rim_category_id
    params[:product_category_id] = $last_data.product_category_id
    params[:root_product_category_id] = $last_data.root_product_category_id
=end
    @product = Product.new(session[:last_product_record])
    if rpc_id = params[:root_product_category_id]
      @product.root_product_category_id = rpc_id.to_i
    end
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        session[:last_product_record] = product_params.dup
        format.html { redirect_to @product, notice: '新增产品数据完成' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: '编辑产品数据完成' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: '删除产品数据完成' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:product_category_id, :product_no, :name, :description, :spec, :brand, :material_id, :surface_craft_id, :water_absrp_rate_id, :thickness, :shape_id, :color_id, :cases_per_pallet, :base_unit_id, :unit_weight, :unit_area, :business_unit_id, :packing_unit, :package_weight, :rim_category_id, :root_product_category_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<%= render 'form' %>

<%#= link_to 'Show', @product %> 
<%#= link_to 'Back', products_path %>

app/views/products/index.html.erb
  <div class="col-md-11 col-xs-11 cont_right" style="margin-left:8.3333333333%;">
    <%= form_tag products_path, :method => 'get' do %>
    <div class="col-md-5 col-xs-5 ser_h">
      <%= text_field_tag :product, params[:product], class: 'form-control', placeholder: "输入你要查找的产品编号或产品名称"%>
    </div>
    <div class="col-md-3 col-xs-6 ser_h">
      <div class="col-md-6 col-xs-6 text-center line_h35">产品品类</div>
      <div class="col-md-6 col-xs-6 padt10">
        <%= select_tag(:category, 
            options_for_select([['请选择',0],['瓷砖',1],['马赛克',2],['卫浴',3],['五金',4]]),{:class => 'form-control'}
            )
        %>
      </div>
    </div>
    <div class="col-md-3 col-xs-6 ser_h">
      <div class="col-md-6 col-xs-6 text-center line_h35">产品规格</div>
      <div class="col-md-6 col-xs-6 padt10">
        <%= text_field_tag :spec, params[:spec], class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-1 col-xs-1 ser_h" style="background:#fff;">
      <%= submit_tag "搜索", :name => nil, class: "btn btn-default", 
                            style: "background:#78909c;color:#fff;"
      %>
    </div>
    <% end %>

    
    <div class="col-md-12 col-xs-12 mt20">
      <ul class="nav nav-tabs" id="myTab" style="font-size:18px;">
        <li class="active"><a href="#ceramic">瓷砖</a></li>
        <li><a href="#mosaic">马赛克</a></li>
        <li><a href="#bathroom">卫浴</a></li>
        <li><a href="#hardware">五金</a></li>
        <li><a href="#furniture">家具</a></li>
        <li><a href="#electrical_material">电工材料</a></li>
        <li><a href="#pipe">管材</a></li>
        <li><a href="#board">板材</a></li>
        <li><a href="#wallpaper">墙纸</a></li>
        <li><a href="#auxiliary_material">辅助材料</a></li>
        <li><a href="#wood_floor">木地板</a></li>
        <li><a href="#lighting">灯饰</a></li>
        <li><a href="#doors_and_windows">门窗</a></li>
        <li><a href="#ceiling">天花吊顶</a></li>
        <li><a href="#electric_appliance">电器</a></li>
        <li><a href="#cupboard">橱柜</a></li>
        <li><a href="#paintcoating">油漆涂料</a></li>
        <li><a href="#custom_wardrobe">订制衣柜</a></li>
        <li><a href="#stone">石材</a></li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="ceramic">
          <div class="col-md-12 col-xs-12 mt20">
            <%= link_to '新增瓷砖', new_product_path(root_product_category_id: '1'),class: 'creat' %>
          </div>
          <div class="col-md-12 col-xs-12 text-center th_h" style="margin-top:20px;padding-left:0;padding-right:0;">
            <table style="width:100%;">
              <thead>
                <tr>
                  <% @title = ProductField.select('title').where(tabtype: 'ceramic') %>
                  <th class="col-md-2 text-center col-xs-2">
                    <%= @title.rewhere(position: '2').as_json(only: 'title')[0]['title'] %>
                  </th>
                  <th class="col-md-2 text-center col-xs-2">
                    <%= @title.rewhere(position: '1').as_json(only: 'title')[0]['title'] %>
                  </th>
                  <th class="col-md-2 text-center col-xs-2">
                    <%= @title.rewhere(position: '3').as_json(only: 'title')[0]['title'] %>
                  </th>
                  <th class="col-md-2 text-center col-xs-2">
                    <%= @title.rewhere(position: '5').as_json(only: 'title')[0]['title'] %>
                  </th>
                  <th class="col-md-3 text-center col-xs-4">操作</th>
                  <th class="col-md-2 text-center col-xs-4">添加价格</th>
                </tr>
              </thead>

              <tbody>
                <% @field = ProductField.select('field').where(tabtype: 'ceramic') %>
                <% @products.each do |product| %>
                  <tr>
                    <td><%= product.send(@field.rewhere(position: '2').as_json(only: 'field')[0]['field']) %></td>
                    <td><%= product.product_category.try(:name) %></td>
                    <td><%= product.send(@field.rewhere(position: '3').as_json(only: 'field')[0]['field']) %></td>
                    <td><%= product.send(@field.rewhere(position: '5').as_json(only: 'field')[0]['field']) %></td>
                    <td><%= link_to '查看', product ,class: 'text-center'%>&nbsp;&nbsp;<%= link_to '编辑', edit_product_path(product) ,class: 'text-center'%>&nbsp;&nbsp;<%= link_to '删除', product, method: :delete, data: { confirm: '真的要删除资料吗?' } ,class: 'text-center'%></td>
                    <td><%= link_to '添加', new_price_management_path(@price_management, product_no: product.product_no) %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <br>
            <%= will_paginate @products %> 
          </div>
        </div>
        <div class="tab-pane" id="mosaic">
          <div class="col-md-12 col-xs-12 mt20">
            <%= link_to '新增马赛克', new_product_path(root_product_category_id: '101'),class: 'creat' %>
          </div>
          <div class="col-md-12 col-xs-12 text-center th_h" style="margin-top:20px;padding-left:0;padding-right:0;">
            <table style="width:100%;">
              <thead>
                <tr>
                  <% @Title = ProductField.select('title').where(tabtype: 'mosaic') %>
                  <th class="col-md-2 text-center col-xs-2">
                    <%= @Title.rewhere(position: '2').as_json(only: 'title')[0]['title'] %>
                  </th>
                  <th class="col-md-2 text-center col-xs-2">
                    <%= @Title.rewhere(position: '1').as_json(only: 'title')[0]['title'] %>
                  </th>
                  <th class="col-md-2 text-center col-xs-2">
                    <%= @Title.rewhere(position: '3').as_json(only: 'title')[0]['title'] %>
                  </th>
                  <th class="col-md-2 text-center col-xs-2">
                    <%= @Title.rewhere(position: '5').as_json(only: 'title')[0]['title'] %>
                  </th>
                  <th class="col-md-3 text-center col-xs-4">操作</th>
                  <th class="col-md-2 text-center col-xs-4">添加价格</th>
                </tr>
              </thead>

              <tbody>
                <% @Field = ProductField.select('field').where(tabtype: 'mosaic') %>
                <% @mosaic.each do |product| %>
                  <tr>
                    <td><%= product.send(@Field.rewhere(position: '2').as_json(only: 'field')[0]['field']) %></td>
                    <td><%= product.product_category.try(:name) %></td>
                    <td><%= product.send(@Field.rewhere(position: '3').as_json(only: 'field')[0]['field']) %></td>
                    <td><%= product.send(@Field.rewhere(position: '5').as_json(only: 'field')[0]['field']) %></td>
                    <td><%= link_to '查看', product ,class: 'text-center'%>&nbsp;&nbsp;<%= link_to '编辑', edit_product_path(product, root_product_category_id: '101'), class: 'text-center'%>&nbsp;&nbsp;<%= link_to '删除', product, method: :delete, data: { confirm: '真的要删除资料吗?' } ,class: 'text-center'%></td>
                    <td><%= link_to '添加', new_price_management_path(@price_management, product_no: product.product_no) %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <br>
            <%#= will_paginate @mosaic %> 
          </div>
        </div>
        <div class="tab-pane" id="bathroom">
          <div class="col-md-12 col-xs-12 mt20">
            <%= link_to '新增卫浴', new_product_path,class: 'creat' %>
          </div>  
        </div>
        <div class="tab-pane" id="hardware">
          <div class="col-md-12 col-xs-12 mt20">
            <%= link_to '新增五金', new_product_path,class: 'creat' %>
          </div>
        </div>
        <div class="tab-pane" id="furniture">
          <div class="col-md-12 col-xs-12 mt20">
            <%= link_to '新增家具', new_product_path,class: 'creat' %>
          </div>
        </div>
        <div class="tab-pane" id="electrical_material">
          <div class="col-md-12 col-xs-12 mt20">
            <%= link_to '新增电工材料', new_product_path,class: 'creat' %>
          </div>
        </div>
        <div class="tab-pane" id="pipe">
          <div class="col-md-12 col-xs-12 mt20">
            <%= link_to '新增管材', new_product_path,class: 'creat' %>
          </div>
        </div>
        <div class="tab-pane" id="board">
          <div class="col-md-12 col-xs-12 mt20">
            <%= link_to '新增板材', new_product_path,class: 'creat' %>
          </div>
        </div>
        <div class="tab-pane" id="wallpaper">
          <div class="col-md-12 col-xs-12 mt20">
            <%= link_to '新增墙纸', new_product_path,class: 'creat' %>
          </div>
        </div>
        <div class="tab-pane" id="auxiliary_material">
          <div class="col-md-12 col-xs-12 mt20">
            <%= link_to '新增辅助材料', new_product_path,class: 'creat' %>
          </div>
        </div>
        <div class="tab-pane" id="wood_floor">
          <div class="col-md-12 col-xs-12 mt20">
            <%= link_to '新增木地板', new_product_path,class: 'creat' %>
          </div>
        </div>
        <div class="tab-pane" id="lighting">
          <div class="col-md-12 col-xs-12 mt20">
            <%= link_to '新增灯饰', new_product_path,class: 'creat' %>
          </div>
        </div>
        <div class="tab-pane" id="doors_and_windows">
          <div class="col-md-12 col-xs-12 mt20">
            <%= link_to '新增门窗', new_product_path,class: 'creat' %>
          </div>
        </div>
        <div class="tab-pane" id="ceiling">
          <div class="col-md-12 col-xs-12 mt20">
            <%= link_to '新增天花吊顶', new_product_path,class: 'creat' %>
          </div>
        </div>
        <div class="tab-pane" id="electric_appliance">
          <div class="col-md-12 col-xs-12 mt20">
            <%= link_to '新增电器', new_product_path,class: 'creat' %>
          </div>
        </div>
        <div class="tab-pane" id="cupboard">
          <div class="col-md-12 col-xs-12 mt20">
            <%= link_to '新增橱柜', new_product_path,class: 'creat' %>
          </div>
        </div>
        <div class="tab-pane" id="paintcoating">
          <div class="col-md-12 col-xs-12 mt20">
            <%= link_to '新增油漆涂料', new_product_path,class: 'creat' %>
          </div>
        </div>
        <div class="tab-pane" id="custom_wardrobe">
          <div class="col-md-12 col-xs-12 mt20">
            <%= link_to '新增订制衣柜', new_product_path,class: 'creat' %>
          </div>
        </div>
        <div class="tab-pane" id="stone">
          <div class="col-md-12 col-xs-12 mt20">
            <%= link_to '新增石材', new_product_path,class: 'creat' %>
          </div>
        </div>
      </div>
    </div>

  <script>
    $(function () {
      $('#myTab a:first').tab('show');
    })
    $('#myTab a').click(function (e) {
      e.preventDefault();
    $(this).tab('show');
  })
  </script>

app/views/products/new.html.erb
<%= render 'form' %>

app/views/products/show.html.erb
  <div class="col-md-11 col-xs-11 cont_right" style="margin-left:8.3333333333%;margin-top:20px;">
    <%= form_for(@product) do |f| %>
      <div class="row">
        <div class="col-md-4 field col-xs-12">
          <div class="col-md-4 col-xs-4 pad_line"><%= f.label :产品编号 %></div>
          <div class="col-md-8 col-xs-8"><%= f.text_field :product_no,class: 'form-control',disabled: 'disabled'%></div>
        </div>
        <div class="field col-md-4 col-xs-12">
          <div class="col-md-4 col-xs-4 pad_line"><%= f.label :产品名称 %></div>
          <div class="col-md-8 col-xs-8"><%= f.text_field :name,class: 'form-control',disabled: 'disabled'%></div>
        </div>
        <div class="field col-md-4 col-xs-12">
          <div class="col-md-4 col-xs-4 pad_line"><%= f.label :产品说明 %></div>
          <div class="col-md-8 col-xs-8"><%= f.text_area :description, rows: "5",class: 'form-control',disabled: 'disabled',style: 'height:34px;' %></div>
        </div>
        <div class="field col-md-4 col-xs-12">
          <div class="col-md-4 col-xs-4 pad_line"><%= f.label :产品规格 %></div>
          <div class="col-md-8 col-xs-8"><%= f.text_field :spec,class: 'form-control',disabled: 'disabled' %></div>
        </div>
        <div class="field col-md-4 col-xs-12">
          <div class="col-md-4 col-xs-4 pad_line"><%= f.label :品牌 %></div>
          <div class="col-md-8 col-xs-8"><%= f.text_field :brand,class: 'form-control',disabled: 'disabled' %></div>
        </div>
        <div class="field col-md-4 col-xs-12">
          <div class="col-md-4 col-xs-4 pad_line"><%= f.label :材质 %></div>
          <div class="col-md-8 col-xs-8">
            <%= f.text_field :material_id, value: f.object.material.try(:name),class: 'form-control',disabled: 'disabled' %>
          </div>
        </div>
        <div class="field col-md-4 col-xs-12">
          <div class="col-md-4 col-xs-4 pad_line"><%= f.label :表面工艺 %></div>
          <div class="col-md-8 col-xs-8">
            <%= f.text_field :surface_craft_id, value: f.object.surface_craft.try(:name),class: 'form-control',disabled: 'disabled' %>
          </div>
        </div>
        <div class="field col-md-4 col-xs-12">
          <div class="col-md-4 col-xs-4 pad_line"><%= f.label :吸水率 %></div>
          <div class="col-md-8 col-xs-8">
            <%= f.text_field :water_absrp_rate_id, value: f.object.water_absrp_rate.try(:name),class: 'form-control',disabled: 'disabled' %>
          </div>
        </div>
        <div class="field col-md-4 col-xs-12">
          <div class="col-md-4 col-xs-4 pad_line"><%= f.label :厚度 %></div>
          <div class="col-md-8 col-xs-8"><%= f.text_field :thickness,class: 'form-control',disabled: 'disabled' %></div>
        </div>
        <div class="field col-md-4 col-xs-12">
          <div class="col-md-4 col-xs-4 pad_line"><%= label_tag :shape_id, "形状" %></div>
          <div class="col-md-8 col-xs-8">
            <%= f.text_field :shape_id, value: f.object.shape.try(:name),class: 'form-control',disabled: 'disabled' %>
          </div>
        </div>
        <div class="field col-md-4 col-xs-12">
          <div class="col-md-4 col-xs-4 pad_line"><%= label_tag :color_id, "颜色" %></div>
          <div class="col-md-8 col-xs-8">
            <%= f.text_field :color_id, value: f.object.color.try(:name),class: 'form-control',disabled: 'disabled' %>
          </div>
        </div>
        <div class="filed col-md-4">
          <div class="col-md-4 col-xs-4 pad_line"><%= f.label :打托数量 %></div>
          <div class="col-md-8 col-xs-8"><%= f.number_field :cases_per_pallet,class: 'form-control',disabled: 'disabled' %></div>
        </div>
      </div>
      <div class="row">
        <div class="field col-md-4 col-xs-12">
          <div class="col-md-4 col-xs-4 pad_line"><%= f.label :基本单位 %></div>
          <div class="col-md-8 col-xs-8"><%= f.text_field :base_unit_id, value: BaseUnit.find(@product.base_unit_id).name,class: 'form-control',disabled: 'disabled' %></div>
        </div>
        <div class="field col-md-4 col-xs-12">
          <div class="col-md-4 col-xs-4 pad_line"><%= f.label :单位重量 %></div>
          <div class="col-md-8 col-xs-8"><%= f.text_field :unit_weight,class: 'form-control',disabled: 'disabled' %></div>
        </div>
        <div class="field col-md-4 col-xs-12">
          <div class="col-md-4 col-xs-4 pad_line"><%= f.label :单位面积 %></div>
          <div class="col-md-8 col-xs-8"><%= f.text_field :unit_area,class: 'form-control',disabled: 'disabled' %></div>
        </div>
        <div class="field col-md-4 col-xs-12">
          <div class="col-md-4 col-xs-4 pad_line"><%= f.label :业务单位 %></div>
          <div class="col-md-8 col-xs-8"><%= f.text_field :business_unit_id, value: BusinessUnit.find(@product.business_unit_id).name,class: 'form-control',disabled: 'disabled' %></div>
        </div>
        <div class="field col-md-4 col-xs-12">
          <div class="col-md-4 col-xs-4 pad_line"><%= f.label :包装单位 %></div>
          <div class="col-md-8 col-xs-8"><%= f.text_field :packing_unit,class: 'form-control',disabled: 'disabled' %></div>
        </div>
        <div class="field col-md-4 col-xs-12">
          <div class="col-md-4 col-xs-4 pad_line"><%= f.label :包装重量 %></div>
          <div class="col-md-8 col-xs-8"><%= f.text_field :package_weight,class: 'form-control',disabled: 'disabled' %></div>
        </div>
      </div>
      <div class="row">
        <div class="field col-md-4 col-xs-12">
          <div class="col-md-4 col-xs-4 pad_line"><%= f.label :装边类型 %></div>
           <div class="col-md-8 col-xs-8">
            <%= f.text_field :rim_category_id, value: f.object.rim_category.try(:name),
                class: 'form-control',disabled: 'disabled' %>
           </div>
        </div>
      </div>
      <div class="row mt40">
        <div class="col-md-4 form-group field">
          <div class="col-md-4 col-xs-4 pad_line"><%= f.label :产品品类 %></div>
          <div class="col-md-8 col-xs-8"><%= f.text_field :product_category_id, value: @product.product_category.try(:name), class: 'form-control', disabled: 'disabled'%></div>
        </div>
      </div>
      <div class="row" style="margin-top:20px;margin-left:20px;">
      <div class="actions">
        <%= link_to '编辑', edit_product_path(@product),class: 'btn btn-default' %>
        <%= link_to '返回', products_path,class: 'btn btn-default' %>
      </div>
      </div>
    <% end %>