config/routes.rb
Rails.application.routes.draw do

  get 'series_images/index' , to: 'series_images#index', as: 'series_images'

  get 'series_images/new'

  get 'series_images/create'

  get 'series_images/update'

  post 'series_images/update'

  resources :skus
  get '/price_managements/index', :controller => 'price_managements', :action => 'index'
  post '/price_managements/index', :controller => 'price_managements', :action => 'index'
  get '/product_images/index', :controller => 'product_images', :action => 'index'
  post '/product_images/index', :controller => 'product_images', :action => 'index'
  get '/site_skus/index', :controller => 'site_skus', :action => 'index'
  post '/site_skus/index', :controller => 'site_skus', :action => 'index'
  get '/baby_managements/index', :controller => 'baby_managements', :action => 'index'
  post '/baby_managements/index', :controller => 'baby_managements', :action => 'index'
    
  resources :baby_managements
  resources :product_managements
  resources :price_managements
  resources :users
  resources :products
  resources :site_skus
  root 'sessions#create'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :product_images

end

app/models/base_unit.rb
# == Schema Information
#
# Table name: base_units
#
#  id         :integer          not null, primary key
#  name       :string
#  position   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class BaseUnit < ActiveRecord::Base
  has_many :product_category_base_units
end

app/models/business_unit.rb
# == Schema Information
#
# Table name: business_units
#
#  id         :integer          not null, primary key
#  name       :string
#  position   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class BusinessUnit < ActiveRecord::Base
end

app/models/color.rb
# == Schema Information
#
# Table name: colors
#
#  id           :integer          not null, primary key
#  name         :string
#  position     :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  english_name :string
#

class Color < ActiveRecord::Base
end

app/models/currency.rb
class Currency < ActiveRecord::Base
  has_many :price_management
end

app/models/image.rb
# == Schema Information
#
# Table name: images
#
#  id         :integer          not null, primary key
#  md5        :string
#  file_size  :integer
#  filename   :string
#  image      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Image < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  has_many :product_images
end

app/models/material.rb
# == Schema Information
#
# Table name: materials
#
#  id         :integer          not null, primary key
#  name       :string
#  position   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Material < ActiveRecord::Base
  has_many :product_category_materials
end

app/models/price_unit.rb
class PriceUnit < ActiveRecord::Base
  has_many :price_management
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id                  :integer          not null, primary key
#  product_category_id :integer
#  product_no          :string
#  name                :string
#  description         :text
#  spec                :string
#  brand               :string
#  water_absrp_rate_id :integer
#  thickness           :decimal(, )
#  shape_id            :integer
#  color_id            :integer
#  cases_per_pallet    :integer
#  unit_weight         :decimal(, )
#  unit_area           :decimal(, )
#  package_weight      :decimal(, )
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  surface_craft_id    :integer
#  base_unit_id        :integer
#  business_unit_id    :integer
#  material_id         :integer
#  packing_unit        :integer
#  tabtype             :string
#

class Product < ActiveRecord::Base
  belongs_to :product_category
  belongs_to :root_product_category, class_name: "ProductCategory", foreign_key: :root_product_category_id
  belongs_to :rim_category
  belongs_to :material
  belongs_to :surface_craft
  belongs_to :water_absrp_rate
  belongs_to :shape
  belongs_to :color
  has_many :price_management, dependent: :destroy
  has_many :product_images, dependent: :destroy
  has_many :site_sku, dependent: :destroy
  has_many :sku, dependent: :destroy
  has_many :baby_management, dependent: :destroy

  validates_presence_of :product_no, :message => "产品编号不能为空"
  validates_presence_of :product_category_id, :message => "产品品类不能为空"
end

app/models/product_field.rb
# == Schema Information
#
# Table name: product_fields
#
#  id         :integer          not null, primary key
#  tabtype    :string
#  field      :string
#  title      :string
#  datetype   :string
#  position   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ProductField < ActiveRecord::Base
end

app/models/product_image.rb
# == Schema Information
#
# Table name: product_images
#
#  id                        :integer          not null, primary key
#  position                  :integer
#  image_id                  :integer
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#  series                    :text
#  size                      :string
#  product_image_category_id :integer
#  sku_id                    :integer
#

class ProductImage < ActiveRecord::Base
  belongs_to :image
  belongs_to :sku
  belongs_to :product_image_category
  belongs_to :product

  attr_accessor :image_file
  before_save :take_care_of_image

  private

  def take_care_of_image
    return unless image_file = self.image_file

    file_path = image_file.tempfile.path
    md5 = Digest::MD5.file(file_path).to_s
    if found= Image.find_by(md5: md5)
      self.image = found
    else
      self.image = Image.create(
        md5: md5,
        filename: image_file.original_filename,
        file_size: image_file.size,
        image: image_file
      )
    end
  end
end

app/models/rim_category.rb
class RimCategory < ActiveRecord::Base
  has_many :products
end

app/models/search.rb
class Search < RailsSimpleSearch::Base
end

app/models/shape.rb
# == Schema Information
#
# Table name: shapes
#
#  id         :integer          not null, primary key
#  name       :string
#  position   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Shape < ActiveRecord::Base
  has_many :product_category_shapes
end

app/models/site.rb
# == Schema Information
#
# Table name: sites
#
#  id         :integer          not null, primary key
#  code       :string
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Site < ActiveRecord::Base
end

app/models/site_sku.rb
# == Schema Information
#
# Table name: site_skus
#
#  id         :integer          not null, primary key
#  site_id    :integer
#  sku        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  product_id :integer
#  selected   :boolean
#

class SiteSku < ActiveRecord::Base
  belongs_to :product
  belongs_to :sku
end

app/models/sku.rb
# == Schema Information
#
# Table name: skus
#
#  id         :integer          not null, primary key
#  product_id :integer
#  level      :string
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Sku < ActiveRecord::Base
  has_many :product_images, dependent: :destroy
  has_many :site_skus, dependent: :destroy
  belongs_to :product

  accepts_nested_attributes_for :product_images
  accepts_nested_attributes_for :site_skus
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  employee_number :string
#  name            :string
#  mobile          :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  admin           :boolean          default(FALSE)
#

class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password validations: false
end

app/models/warehouse.rb
# == Schema Information
#
# Table name: warehouses
#
#  id         :integer          not null, primary key
#  name       :string
#  position   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Warehouse < ActiveRecord::Base
	
end

app/helpers/skus_helper.rb
module SkusHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
  <style>
    #notice{position:relative;top:13px;text-align:center;border:1px solid #ccc; line-height:33px;background:#eeeeee;border-radius:4px;}
  </style>
  <div class="row main_nav mar0">
    <div class="col-md-6 col-xs-6"><h4>资源管理中心</h4></div>
    <div class="col-md-6 col-xs-6 text-right">
      <h4><span class="glyphicon glyphicon-user"></span>&nbsp;<%= session[:employee_number] %>&nbsp;&nbsp;<span class="glyphicon glyphicon-log-out"></span>&nbsp;
      	<%= link_to '退出',logout_path,method: :delete %>
      </h4>
    </div> 
  </div>
  <div style="height:49px;"></div>
  <% if notice %>
      <div class="col-md-11 col-xs-11" style="margin-left:8.3333333333%;">
        <p id="notice" class="notice"><%= notice %></p>
      </div>
  <% end %>

app/views/layouts/_menu.html.erb
  <div class="row">
    <div class="col-md-1 col-xs-1 cont_left pad0">
      <ul class="list-unstyled" id="menu">
        <li>
          <a data-toggle="collapse" data-parent="#accordion" 
             href="#collapseOne">
            商品录入<span class="glyphicon glyphicon-align-justify right"></span>
          </a>
          <div id="collapseOne" class="panel-collapse collapse in">
            <ul style="padding-left:0;">
              <li style="padding-left:0;"><a href="/products">非套裝</a></li>
              <li style="padding-left:0;"><a>套裝</a></li>
            </ul>
          </div>
        </li>
        <% if params[:controller] == "product" || session[:employee_number] == "0200361" %>
          <li><%= link_to '价格管理',price_managements_path %></li>
        <% end %>
        <% if params[:controller] == "product" || session[:employee_number] != "0200361" %>
          <li><%= link_to '素材管理',product_images_path %></li>
        <% end %>
        <% if params[:controller] == "product" || session[:employee_number] != "0200361" %>
          <li><%= link_to '商品管理',site_skus_path %></li>
        <% end %>
        <% if params[:controller] == "product" || session[:employee_number] != "0200361" %>
          <li><%= link_to '宝贝管理',baby_managements_path %></li>
        <% end %>
        <% if params[:controller] == "product" || session[:employee_number] != "0200361" %>
          <li><%= link_to '系列图管理',series_images_path %></li>
        <% end %>
        <% if params[:controller] == "users" || session[:employee_number] == "admin" %>
          <li><%= link_to '用户管理',users_path %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <script type="text/javascript">
  var urlstr = location.href;
  //alert((urlstr + '/').indexOf($(this).attr('href')));
  var urlstatus=false;
  $("#menu a").each(function () {
    if ((urlstr + '/').indexOf($(this).attr('href')) > -1&&$(this).attr('href')!='') {
      $(this).addClass('cur'); urlstatus = true;
    } else {
      $(this).removeClass('cur');
    }
  });
  if (!urlstatus) {$("#menu a").eq(0).addClass('cur'); }
  $(function () { $('#collapseOne').collapse({
    toggle: true
  })});
  $(function(){
    $("#menu a").click(function(e){
        /*切换折叠指示图标*/
        $(this).find("span").toggleClass("glyphicon-chevron-down");
        $(this).find("span").toggleClass("glyphicon-chevron-up");
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ResourceCenter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller] %> public">
	<% if params[:controller] != "sessions" %>
		<%= render "layouts/header" %>
		<%= render "layouts/menu" %>
	<% end %>
	<%= yield %>
</body>
</html>